# Generated by Django 3.1.4 on 2021-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number_images',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
