# Generated by Django 3.1.4 on 2021-10-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211012_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='link',
            name='time',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
