# Generated by Django 3.1.4 on 2021-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20211013_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='person_phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
